load('0vAllData.mat');
load('0vAllLabels.mat');
X = newdata;
Y = newlabels;
validata = newdata([1:7291/6],:);
validlabel = newlabels([1:7291/6],:);
traindata = validata([1:1215*2/3],:);
trainlabel = validlabel([1:1215*2/3],:);
testdata = validata([811:1215],:);
testlabel = validlabel([811:1215],:);
disp('------------------------------------------C = 1--------------');
errorlinear = SVM(traindata,trainlabel,testdata,testlabel,1,'linear');
disp(errorlinear);
errorpoly = SVM(traindata,trainlabel,testdata,testlabel,1,'polynomial');
disp(errorpoly);
errorrbf = SVM(traindata,trainlabel,testdata,testlabel,1,'rbf');
disp(errorrbf);
disp('------------------------------------------C = 0.1--------------');
errorlinear = SVM(traindata,trainlabel,testdata,testlabel,0.1,'linear');
disp(errorlinear);
errorpoly = SVM(traindata,trainlabel,testdata,testlabel,0.1,'polynomial');
disp(errorpoly);
errorrbf = SVM(traindata,trainlabel,testdata,testlabel,0.1,'rbf');
disp(errorrbf);
disp('------------------------------------------C = 0.01--------------');
errorlinear = SVM(traindata,trainlabel,testdata,testlabel,0.01,'linear');
disp(errorlinear);
errorpoly = SVM(traindata,trainlabel,testdata,testlabel,0.01,'polynomial');
disp(errorpoly);
errorrbf = SVM(traindata,trainlabel,testdata,testlabel,0.01,'rbf');
disp(errorrbf);
disp('------------------------------------------C = 20--------------');
errorlinear = SVM(traindata,trainlabel,testdata,testlabel,20,'linear');
disp(errorlinear);
errorpoly = SVM(traindata,trainlabel,testdata,testlabel,20,'polynomial');
disp(errorpoly);
errorrbf = SVM(traindata,trainlabel,testdata,testlabel,20,'rbf');
disp(errorrbf);
disp('------------------------------------------C = 50--------------');
errorlinear = SVM(traindata,trainlabel,testdata,testlabel,50,'linear');
disp(errorlinear);
errorpoly = SVM(traindata,trainlabel,testdata,testlabel,50,'polynomial');
disp(errorpoly);
errorrbf = SVM(traindata,trainlabel,testdata,testlabel,50,'rbf');
disp(errorrbf);